
project_id = "ndcvvnssrranofnxfcdy"

[functions.sync-cities]
enabled = true
verify_jwt = false
import_map = "./functions/svg-to-jpg/deno.json"
entrypoint = "./functions/svg-to-jpg/index.ts"
static_files=["./functions/svg-to-jpg/magick.wasm"]


[functions.sync-operators]
verify_jwt = false

[functions.sync-buses]
verify_jwt = false

[functions.sync-seat-availability]
verify_jwt = false

[functions.lock-seats]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.fetch-coupons]
verify_jwt = false

[functions.cleanup-locked-seats]
verify_jwt = false

[functions.init-database]
verify_jwt = false

[functions.cron-tasks]
verify_jwt = false
